init_config:

instances:
  - prometheus_url: http://localhost:6060/debug/metrics/prometheus
    namespace: wemix3.0
    metrics:
      - "chain_head_block"
      - "txpool_pending"
      - "p2p_peers"
